### ISSUE TITLE
axis ticks in jenk scale not appearing

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-axis#49]
### Expected Behavior

Expect to see the label for ticks on a Jenks scale 

### Current Behavior

1. If the label for the last tick is near the edge of the visualization, then the label for the last tick does not appear (though the tick mark line does).
2. Labels closely clustered with other labels do not appear and it is not possible to see values for the ticks via tooltips

<img width="353" alt="screen shot 2018-04-04 at 9 48 31 am" src="https://user-images.githubusercontent.com/87581/38311511-5e8593f6-37ed-11e8-85cb-d4fd63f55af8.png">

### Potential suggestion
Maybe an alternative representation like the one below could be a useful option as a legend for jenks scales to avoid these issues?
![cancer_rates_jenks](https://user-images.githubusercontent.com/87581/38312014-9893c706-37ee-11e8-8e2c-85896d595fb0.jpg)

### Steps to Reproduce (for bugs)

1. https://jsfiddle.net/5f639ph1/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: OS X

**Comment by davelandry** [comment]
That last tick bug is assumed dead in the latest release: https://github.com/d3plus/d3plus-legend/releases/tag/v0.8.17 @jspeis please double check that one in your environment for us.

As for the super-close labels, I think you're right that either a tooltip or using our standard `Legend` instead of `ColorScale` would be preferred. I've created matching issues in `d3plus-legend`, and hopefully @nbond211 can tackle these next week:
* https://github.com/d3plus/d3plus-legend/issues/69
* https://github.com/d3plus/d3plus-legend/issues/70
